### PR TITLE
Fix Flaky Tests

### LINKED ISSUE #26: ValkeyGlideClusterConnectionCommandsIntegrationTests.testClusterGetClusterInfo is flaky with github runner
Error:  io.valkey.springframework.data.valkey.connection.valkeyglide.ValkeyGlideClusterConnectionCommandsIntegrationTests.testClusterGetClusterInfo -- Time elapsed: 0.008 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 4L
 but was: 5L
	at io.valkey.springframework.data.valkey.connection.valkeyglide.ValkeyGlideClusterConnectionCommandsIntegrationTests.testClusterGetClusterInfo(ValkeyGlideClusterConnectionCommandsIntegrationTests.java:278)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

### PR DESCRIPTION
**Pull request by jeremyprime**
## Summary

Updates the following flaky tests that sometimes fail:
- `ValkeyGlideClusterConnectionCommandsIntegrationTests.testClusterGetClusterInfo:278` (expects 4, but gets 5)
- `ReactiveValkeyMessageListenerContainerIntegrationTests.multipleListenShouldTrackSubscriptions` (expects null, but gets message)
- `DefaultHyperLogLogOperationsIntegrationTests.sizeShouldCountValuesCorrectly:96` (expects 3, but gets 2)
- `ClusterSlotHashUtilsTests.localCalculationShouldMatchServers:60 » JedisConnection Unexpected end of stream.` (connection is stale/already closed)

Note there is another change in #23 to fix the Maven cache,  This may help with network-related flaky tests:
- `Could not transfer artifact org.jetbrains.kotlin:kotlin-compiler:jar:1.9.25 from/to central`
- `gzip: stdin: not in gzip format` when getting engine binary

Closes #26.

## Testing

Tests pass locally and in CI a couple times (although these tests failed intermittently, so will need to observe over time).

### CODE REVIEW

File: src/test/java/io/valkey/springframework/data/valkey/connection/valkeyglide/ValkeyGlideClusterConnectionCommandsIntegrationTests.java [hunk 1]
```diff
@@ -259,23 +261,27 @@ void testClusterGetMasterReplicaMap() {
...
-        assertThat(clusterInfo.getState()).isIn("ok", "OK");
-        
-        // Verify all slots are assigned
-        assertThat(clusterInfo.getSlotsAssigned()).isEqualTo(16384);
-        assertThat(clusterInfo.getSlotsOk()).isEqualTo(16384);
-        assertThat(clusterInfo.getSlotsFail()).isEqualTo(0);
-        
-        // Verify node count
-        assertThat(clusterInfo.getKnownNodes()).isEqualTo(EXPECTED_TOTAL_NODES);
+        // Wait for all cluster nodes to be available
```
Comment (ikolomi) [inline src/test/java/io/valkey/springframework/data/valkey/connection/valkeyglide/ValkeyGlideClusterConnectionCommandsIntegrationTests.java]: i dont like retrying in the tests - we need to understand why does it happen...

File: src/test/java/io/valkey/springframework/data/valkey/connection/ClusterSlotHashUtilsTests.java [hunk 2]
```diff
@@ -51,20 +51,20 @@ public ClusterSlotHashUtilsTests(JedisCluster cluster) {
...
-			assertThat(slot)
-					.describedAs("Expected slot for key '%s' to be %s but server calculated %s", key, slot, serverSlot)
-					.isEqualTo(serverSlot.intValue());
+				assertThat(slot)
+						.describedAs("Expected slot for key '%s' to be %s but server calculated %s", key, slot, serverSlot)
+						.isEqualTo(serverSlot.intValue());
+			}
 		}
-
-		jedis.close();
```
Comment (ikolomi) [inline src/test/java/io/valkey/springframework/data/valkey/connection/ClusterSlotHashUtilsTests.java]: why is this code problematic - should not the jedis object be explicitly closed?

**Comment by ikolomi** [comment]
1. I would not touch the existing bugs in SpringDataRedis until we stabilize or at least after alpha
2. .untillAsserted() should be used as a last option - why do we even need to retry. Lets try to fix the root cause

File: src/test/java/io/valkey/springframework/data/valkey/connection/ClusterSlotHashUtilsTests.java (hunk 2 above)
Comment (jeremyprime) [reply src/test/java/io/valkey/springframework/data/valkey/connection/ClusterSlotHashUtilsTests.java]: This issue does not happen as often, but seems to be caused by the connection pool closing the connection prematurely sometimes so it fails when `jedis.close()` is explicitly called on an already closed connection.  The try-with-resources closes the connection without throwing an error in case it was already closed.

File: src/test/java/io/valkey/springframework/data/valkey/listener/ReactiveValkeyMessageListenerContainerIntegrationTests.java [hunk 3]
```diff
@@ -334,12 +335,15 @@ void multipleListenShouldTrackSubscriptions() throws Exception {
...
 		c2Subscription.dispose();
 
-		Thread.sleep(500);
-
 		doPublish(CHANNEL1.getBytes(), MESSAGE.getBytes());
 
-		assertThat(c1Collector.poll(5, TimeUnit.SECONDS)).isNotNull();
-		assertThat(c2Collector.poll(100, TimeUnit.MILLISECONDS)).isNull();
+		// Wait for active subscription to receive message
+		await().atMost(Duration.ofSeconds(5))
```
[the remark this answers is not in the document]
Comment (jeremyprime) [reply src/test/java/io/valkey/springframework/data/valkey/listener/ReactiveValkeyMessageListenerContainerIntegrationTests.java]: It takes time for the message to be propagated and for the disposed subscriber to stop listening, which is why they originally had a 0.5s sleep.  But that is not enough sometimes and the disposed subscriber still gets the message when it should not.  A larger sleep or retry allows the subscription cleanup to complete before the message is sent.
